package com.jobportal.Utility;

public class Data {
    public static String OTPBody(String otp, String name) {
        return "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>OTP Verification</title>\n"
                + "    <style>\n"
                + "        body {\n"
                + "            display: flex;\n"
                + "            justify-content: center;\n"
                + "            align-items: center;\n"
                + "            min-height: 100vh;\n"
                + "            background-color: #fffaf0;\n"
                + "            font-family: Arial, sans-serif;\n"
                + "            padding: 20px;\n"
                + "            margin: 0;\n"
                + "        }\n"
                + "        .container {\n"
                + "            background: #ffffff;\n"
                + "            padding: 25px;\n"
                + "            border-radius: 10px;\n"
                + "            box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);\n"
                + "            text-align: center;\n"
                + "            max-width: 400px;\n"
                + "            width: 100%;\n"
                + "        }\n"
                + "        .title {\n"
                + "            font-size: 22px;\n"
                + "            font-weight: bold;\n"
                + "            color: #e67e22;\n"
                + "        }\n"
                + "        .message {\n"
                + "            color: #444;\n"
                + "            font-size: 16px;\n"
                + "            margin-top: 12px;\n"
                + "        }\n"
                + "        .otp {\n"
                + "            font-size: 28px;\n"
                + "            font-weight: bold;\n"
                + "            color: #d35400;\n"
                + "            background: #fde3a7;\n"
                + "            padding: 12px 24px;\n"
                + "            border-radius: 6px;\n"
                + "            margin-top: 16px;\n"
                + "            letter-spacing: 3px;\n"
                + "            display: inline-block;\n"
                + "        }\n"
                + "        .footer {\n"
                + "            margin-top: 20px;\n"
                + "            font-size: 14px;\n"
                + "            color: #777;\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "        @media (max-width: 480px) {\n"
                + "            .container {\n"
                + "                padding: 20px;\n"
                + "                max-width: 90%;\n"
                + "            }\n"
                + "            .otp {\n"
                + "                font-size: 24px;\n"
                + "                padding: 10px 20px;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "    <div class=\"container\">\n"
                + "        <h2 class=\"title\">Hello, " + name + "!</h2>\n"
                + "        <p class=\"message\">We have sent an OTP to your email. Use the OTP below to verify your email:</p>\n"
                + "        <div class=\"otp\">" + otp + "</div>\n"
                + "    </div>\n"
                + "    <p class=\"footer\">© 2025 JobHook, All Rights Reserved.</p>\n"
                + "</body>\n"
                + "</html>";
    }
}
